# Generated by Django 5.2.4 on 2025-07-25 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_management', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaints',
        ),
    ]
